name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # container: node:18.16.0

    services:
      libsql:
        image: ghcr.io/libsql/sqld:latest
        ports:
          - 8888:8080

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          cache: npm

      - name: Install Wing
        run: npm i -g winglang

      - name: Install
        run: npm ci
